name: "Strawberry Fields"
markdown: kramdown
permalink: :title
exclude: [README.md, LICENSE, Makefile]

# Information for the Atom feed
strawberry-fields:
   author: "HJKUNST"
   email: "whiskyhibiki1@gmail.com"

url: "https://hjkunst.github.io/"
baseurl: ""